controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true"""

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller_right:
      type: velocity_controllers/JointGroupVelocityController

    velocity_controller_left:
      type: velocity_controllers/JointGroupVelocityController


joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    state_interfaces:
      - velocity
      - position


velocity_controller_right:
  ros__parameters:
    joints:
      - right_wheel_joint
    command_interfaces:
      - velocity


velocity_controller_left:
  ros__parameters:
    joints:
      - left_wheel_joint
    command_interfaces:
      - velocity