controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller_r:
      type: velocity_controllers/JointGroupVelocityController

    velocity_controller_l:
      type: velocity_controllers/JointGroupVelocityController


joint_broadcaster:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
    state_interfaces:
      - velocity
      - position


velocity_controller_r:
  ros__parameters:
    joints:
      - wheel_right_joint
    command_interfaces:
      - velocity


velocity_controller_l:
  ros__parameters:
    joints:
      - wheel_left_joint
    command_interfaces:
      - velocity