# =========================================================
# Archivo: controllers.yaml
# Descripción:
#   Configuración de controladores para ros2_control y Gazebo
#   - Define el controller_manager y los controladores de velocidad y estado articular
#   - Especifica las interfaces y las juntas que controla cada controlador
# =========================================================

controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller_l:
      type: velocity_controllers/JointGroupVelocityController

    velocity_controller_r:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - caster_wheel_support
      - caster_wheel
    state_interfaces:
      - position
      - velocity


velocity_controller_l:
  ros__parameters:
    joints:
      - left_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


velocity_controller_r:
  ros__parameters:
    joints:
      - right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity