<?xml version="1.0"?>
<robot name="diffbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Parámetros reutilizables -->
    <xacro:property name="chassis_mass" value="0.8"/>
    <xacro:property name="chassis_length" value="0.195"/>
    <xacro:property name="chassis_width" value="0.1"/>
    <xacro:property name="chassis_height" value="0.05"/>

    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_separation" value="0.08"/> <!-- Separación media -->

    <!-- Incluir macros -->
    <xacro:include filename="$(find tp1_robot)/urdf/inertial_macros.xacro"/>
    <xacro:include filename="$(find tp1_robot)/urdf/motor.xacro"/>

    <!-- Base del robot -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find tp1_robot)/meshes/chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Macro de ruedas -->
    <xacro:macro name="wheel" params="prefix side">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="0.025"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5708 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="0.025"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.15" length="0.025" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="${chassis_length/2 - 0.035} ${side*wheel_separation} -0.025"/>
        </joint>
    </xacro:macro>

    <!-- Instanciar ruedas -->
    <xacro:wheel prefix="left" side="1"/>
    <xacro:wheel prefix="right" side="-1"/>

    <!-- Motores -->
    <xacro:motor prefix="left" chassis_width="${chassis_width}" reflect="false"/>
    <xacro:motor prefix="right" chassis_width="${chassis_width}" reflect="true"/>

    <!-- Plugin de Gazebo -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_diff_drive.so">
            <ros><namespace>/diffbot</namespace></ros>
            <wheel_separation>${wheel_separation * 2}</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
        </plugin>
    </gazebo>

    <!-- Configuración de ros2_control -->
    <ros2_control name="diffbot_controller" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/RobotHWSim</plugin>
        </hardware>
        <joint name="left_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
        <joint name="right_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
    </ros2_control>
</robot>