<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:gazebo="http://www.gazebosim.org/schema/gazebo_urdf">

  <!-- Macro para insertar un motor con inercia -->
  <xacro:macro name="motor" params="prefix chassis_width reflect">
    
    <!-- Parámetros internos -->
    <xacro:property name="motor_mass" value="0.1"/> <!-- Masa del motor (kg) -->
    <xacro:property name="motor_length" value="0.07"/> <!-- Largo del motor (m) -->
    <xacro:property name="motor_width" value="0.025"/> <!-- Ancho del motor (m) -->
    <xacro:property name="motor_height" value="0.025"/> <!-- Altura del motor (m) -->
    <xacro:property name="motor_radius" value="0.0125"/> <!-- Radio de los extremos (m) -->

    <!-- Posición en X (ajustada según reflect) -->
    <xacro:if value="${reflect}">
      <xacro:property name="motor_x" value="${chassis_width/2 - 0.035}"/>
    </xacro:if>
    <xacro:unless value="${reflect}">
      <xacro:property name="motor_x" value="${-chassis_width/2 + 0.035}"/>
    </xacro:unless>

    <!-- Link del motor -->
    <link name="${prefix}_motor_link">
      <visual>
        <origin xyz="${motor_x} -0.01 0" rpy="0 0 0"/>
        <geometry>
          <box size="${motor_length} ${motor_width} ${motor_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="${motor_x} -0.01 0" rpy="0 0 0"/>
        <geometry>
          <box size="${motor_length} ${motor_width} ${motor_height}"/>
        </geometry>
      </collision>

      <!-- Usamos el macro box_inertia con el parámetro correcto 'm' -->
      <xacro:box_inertia m="${motor_mass}" x="${motor_length}" y="${motor_width}" z="${motor_height}"/>
    </link>

    <!-- Joint del motor (fijo al chasis) -->
    <joint name="${prefix}_motor_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_motor_link"/>
      <origin xyz="${motor_x} -0.01 0" rpy="0 0 0"/>
    </joint>

    <!-- Rotor del motor (simulado como cilindro) -->
    <link name="${prefix}_motor_rotor_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${motor_radius}" length="${motor_width}"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${motor_radius}" length="${motor_width}"/>
        </geometry>
      </collision>

      <!-- Usamos el macro cylinder_inertia con el parámetro correcto 'm' -->
      <xacro:cylinder_inertia m="${motor_mass/2}" r="${motor_radius}" h="${motor_width}"/>
    </link>

    <!-- Joint del rotor del motor (fijo al motor) -->
    <joint name="${prefix}_motor_rotor_joint" type="fixed">
      <parent link="${prefix}_motor_link"/>
      <child link="${prefix}_motor_rotor_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>