controller_manager:
  ros__parameters:
    update_rate: 50

    use_sim_time: true

    # Nombre del controlador (debe coincidir con el nombre usado en spawner)
    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffbot_base_controller:
  ros__parameters:
    # Nombres de las articulaciones
    left_wheel_names:
      - left_wheel_joint
    right_wheel_names:
      - right_wheel_joint

    # Parámetros cinemáticos
    wheel_separation: 0.16
    wheel_radius: 0.035
    wheel_separation_multiplier: 1.0
    left_to_right_wheel_radius_diff: 0.0

    # Configuración adicional
    use_stamped_vel: false
    publish_rate: 50.0
    base_frame_id: base_link
    name: diffbot_base_controller